name: Docker镜像同步到阿里云ACR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

env:
  # 确保以下secrets在GitHub仓库设置中正确配置
  ALIYUN_REGISTRY: "${{ secrets.ALIYUN_REGISTRY }}"  # 示例: registry.cn-hangzhou.aliyuncs.com
  ALIYUN_NAMESPACE: "${{ secrets.ALIYUN_NAMESPACE }}"
  ALIYUN_USER: "${{ secrets.ALIYUN_REGISTRY_USER }}"
  ALIYUN_PASSWORD: "${{ secrets.ALIYUN_REGISTRY_PASSWORD }}"

jobs:
  sync-images:
    runs-on: ubuntu-latest
    steps:
    - name: 检出代码
      uses: actions/checkout@v4

    # 关键调试步骤：打印变量和测试网络
    - name: 调试信息
      run: |
        echo "=== 调试信息 ==="
        echo "注册表地址: ${ALIYUN_REGISTRY}"
        echo "命名空间: ${ALIYUN_NAMESPACE}"
        echo "用户名: ${ALIYUN_USER}"
        echo "密码长度: ${#ALIYUN_PASSWORD}"
        echo "=== 网络测试 ==="
        ping -c 2 $ALIYUN_REGISTRY || echo "Ping失败"
        nslookup $ALIYUN_REGISTRY || echo "DNS解析失败"
        curl -I https://$ALIYUN_REGISTRY/v2/ || echo "Curl测试失败"

    # 修复DNS问题的关键步骤
    - name: 配置DNS
      run: |
        echo "=== 配置DNS ==="
        sudo echo "nameserver 8.8.8.8" >> /etc/resolv.conf
        sudo echo "nameserver 114.114.114.114" >> /etc/resolv.conf
        cat /etc/resolv.conf

    - name: 安装Docker CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo usermod -aG docker $USER
        docker --version

    - name: 登录阿里云容器镜像服务
      run: |
        echo "=== 登录ACR ==="
        echo "$ALIYUN_PASSWORD" | docker login \
          -u $ALIYUN_USER \
          --password-stdin \
          $ALIYUN_REGISTRY

    - name: 同步镜像
      run: |
        echo "=== 开始同步镜像 ==="
        while IFS= read -r line || [ -n "$line" ]; do
          [[ -z "$line" || "$line" == \#* ]] && continue
          
          echo "正在拉取: $line"
          docker pull $line
          
          # 处理镜像名称
          original_image=$(echo "$line" | awk '{print $NF}')
          target_image="$ALIYUN_REGISTRY/$ALIYUN_NAMESPACE/$(echo $original_image | sed 's|[/:]|_|g')"
          
          echo "重新标记为: $target_image"
          docker tag $original_image $target_image
          
          echo "推送镜像..."
          docker push $target_image
          
          echo "清理临时镜像..."
          docker rmi $original_image $target_image
        done < images.txt
